#!/bin/bash
if [ git diff --quiet static/js/app.js ] || [ git diff --quiet static/js/froala_editor.min.js ] || [ git diff --quiet static/css/bootstrap.min.css ] || [ git diff --quiet static/css/bootstrapcustom.css ] || [ git diff --quiet static/css/froala_editor.min.css ]
	then
	python s3upload.py
	echo "gone to Amazon"
	fi

git add -A
git commit -m $1
git push
git push heroku master